Add  --ssl-no-revoke to curl example
MicrosoftDocs/microsoft-cloud pull request #20
Opened 2024-12-06 20:59 UTC by bgrainger

On Windows 10, I ran `curl -ix http://localhost:8000 https://jsonplaceholder.typicode.com/posts` as instructed by the documentation.

It produced:

```
HTTP/1.1 200 Connection Established
Content-Length: 0

curl: (35) schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - The revocation function was unable to check revocation for the certificate.
```

Adding `--ssl-no-revoke` bypasses this error with the Dev Proxy self-signed certificate.

2024-12-06 22:13 UTC, Court72 commented
@garrytrinder

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-12-09 10:04 UTC, garrytrinder commented
Thanks for the PR @bgrainger 👍

I can repro on Windows 11.

2024-12-09 10:07 UTC, garrytrinder requested changes

2024-12-09 10:07 UTC, garrytrinder commented on docs/dev/dev-proxy/get-started.md
> +curl --ssl-no-revoke -ix http://localhost:8000 https://jsonplaceholder.typicode.com/posts
We can get the same behaviour with the shorthand option `-k`.

```suggestion
curl -ikx http://localhost:8000 https://jsonplaceholder.typicode.com/posts
```

2024-12-18 16:27 UTC, v-dirichards commented
@bgrainger Would you add a comment to indicate what action to take on this PR? Thanks!

2024-12-18 20:05 UTC, bgrainger commented
The desired action is "merge the PR" (so that the documentation is updated).

2024-12-19 15:39 UTC, merged